export type DataPokemon = {
  name: string;
  color: string;
  skill1?: string;
  skill2?: string;
  species: string;
  height: string;
  weight: string;
  abilities: string;
  genderMale: string;
  genderFemale: string;
  group: string;
  cycle: string;
  img: string;
  hp: string;
  atck: string;
  spAtck: string;
  spDeff: string;
  speed: string;
  total: string;
  showSkill2?: boolean;
};
export const PokemonDataPokemon: DataPokemon[] = [
  {
    name: "sad",
    color: "green",
    skill1: "Grass",
    skill2: "Poison",
    species: "Seed",
    height: "2’3.6” (0.70 cm)",
    weight: "15.2 lbs (6.9 kg)",
    abilities: "Overgrow, Chlorophyl",
    genderMale: "87.5%",
    genderFemale: "12.5%",
    img: "/1.png",
    group: "Monster",
    cycle: "Grass",
    hp: "45",
    atck: "60",
    spAtck: "48",
    spDeff: "66",
    speed: "45",
    total: "317",
  },
  {
    name: "Ivysaur",
    color: "green",
    skill1: "Grass",
    skill2: "Poison",
    species: "Seed",
    height: "2’3.6” (0.70 cm)",
    weight: "15.2 lbs (6.9 kg)",
    abilities: "Overgrow, Chlorophyl",
    genderMale: "87.5%",
    genderFemale: "12.5%",
    img: "./female.svg",
    group: "Monster",
    cycle: "Grass",
    hp: "45",
    atck: "60",
    spAtck: "48",
    spDeff: "66",
    speed: "45",
    total: "317",
  },
  {
    name: "Venusaur",
    color: "green",
    skill1: "Grass",
    skill2: "Poison",
    species: "Seed",
    height: "2’3.6” (0.70 cm)",
    weight: "15.2 lbs (6.9 kg)",
    abilities: "Overgrow, Chlorophyl",
    genderMale: "87.5%",
    genderFemale: "12.5%",
    img: "./female.svg",
    group: "Monster",
    cycle: "Grass",
    hp: "45",
    atck: "60",
    spAtck: "48",
    spDeff: "66",
    speed: "45",
    total: "317",
  },
  {
    name: "Charmander",
    color: "red",
    skill1: "Fire",
    species: "Seed",
    height: "2’3.6” (0.70 cm)",
    weight: "15.2 lbs (6.9 kg)",
    abilities: "Overgrow, Chlorophyl",
    genderMale: "87.5%",
    genderFemale: "12.5%",
    img: "./female.svg",
    group: "Monster",
    cycle: "Grass",
    hp: "45",
    atck: "60",
    spAtck: "48",
    spDeff: "66",
    speed: "45",
    total: "317",
  },
  {
    name: "Charmeleon",
    color: "red",
    skill1: "Grass",
    skill2: "Poison",
    species: "Seed",
    height: "2’3.6” (0.70 cm)",
    weight: "15.2 lbs (6.9 kg)",
    abilities: "Overgrow, Chlorophyl",
    genderMale: "87.5%",
    genderFemale: "12.5%",
    img: "./female.svg",
    group: "Monster",
    cycle: "Grass",
    hp: "45",
    atck: "60",
    spAtck: "48",
    spDeff: "66",
    speed: "45",
    total: "317",
  },
  {
    name: "Blastoise",
    color: "blue",
    skill1: "Water",
    species: "Seed",
    height: "2’3.6” (0.70 cm)",
    weight: "15.2 lbs (6.9 kg)",
    abilities: "Overgrow, Chlorophyl",
    genderMale: "87.5%",
    genderFemale: "12.5%",
    img: "./female.svg",
    group: "Monster",
    cycle: "Grass",
    hp: "45",
    atck: "60",
    spAtck: "48",
    spDeff: "66",
    speed: "45",
    total: "317",
  },
  {
    name: "Wartotle",
    color: "blue",
    skill1: "Water",
    species: "Seed",
    height: "2’3.6” (0.70 cm)",
    weight: "15.2 lbs (6.9 kg)",
    abilities: "Overgrow, Chlorophyl",
    genderMale: "87.5%",
    genderFemale: "12.5%",
    img: "./female.svg",
    group: "Monster",
    cycle: "Grass",
    hp: "45",
    atck: "60",
    spAtck: "48",
    spDeff: "66",
    speed: "45",
    total: "317",
  },
  {
    name: "Pikachu",
    color: "yellow",
    skill1: "Electric",
    species: "Seed",
    height: "2’3.6” (0.70 cm)",
    weight: "15.2 lbs (6.9 kg)",
    abilities: "Overgrow, Chlorophyl",
    genderMale: "87.5%",
    genderFemale: "12.5%",
    img: "./female.svg",
    group: "Monster",
    cycle: "Grass",
    hp: "45",
    atck: "60",
    spAtck: "48",
    spDeff: "66",
    speed: "45",
    total: "317",
  },
];
